# Generated by Django 3.0.2 on 2020-01-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DegreeFreedom', models.IntegerField()),
                ('p_995', models.IntegerField()),
                ('p_99', models.IntegerField()),
                ('p_975', models.IntegerField()),
                ('p_95', models.IntegerField()),
                ('p_9', models.IntegerField()),
                ('p_1', models.IntegerField()),
                ('p_05', models.IntegerField()),
                ('p_025', models.IntegerField()),
                ('p_01', models.IntegerField()),
                ('p_005', models.IntegerField()),
            ],
        ),
    ]
