# Generated by Django 3.0.2 on 2020-01-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitab',
            name='p_005',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chitab',
            name='p_01',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chitab',
            name='p_025',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chitab',
            name='p_05',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chitab',
            name='p_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chitab',
            name='p_9',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chitab',
            name='p_95',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chitab',
            name='p_975',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chitab',
            name='p_99',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chitab',
            name='p_995',
            field=models.FloatField(),
        ),
    ]
